apiVersion: v1
kind: Service
metadata:
  name: {{ include "arca-app.fullname" . }}
  labels:
    {{- include "arca-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "arca-app.selectorLabels" . | nindent 4 }}
